project_id = "zjozesrdjwoeiyidbzop"

[functions.sync-events]
verify_jwt = false

[functions.get-events]
verify_jwt = false

[functions.planetary-time]
verify_jwt = false

[functions.user-clocks]
verify_jwt = true
