interface CosmicLore {
  id: string;
  planetName: string;
  category: 'description' | 'history' | 'civilization' | 'environment' | 'mystery' | 'discovery_story';
  title: string;
  content: string;
  tone: 'scientific' | 'poetic' | 'mysterious' | 'adventure' | 'documentary';
  length: 'short' | 'medium' | 'long';
  tags: string[];
  generated: boolean;
  timestamp: string;
}

interface LoreGenerationRequest {
  planetData: {
    name: string;
    hostStar?: string;
    discoveryYear?: number;
    discoveryMethod?: string;
    planetRadius?: number;
    planetMass?: number;
    temperature?: number;
    distanceFromEarth?: number;
    habitableZone?: boolean;
    orbitalPeriod?: number;
  };
  category: CosmicLore['category'];
  tone: CosmicLore['tone'];
  length: CosmicLore['length'];
}

const API_BASE_URL = 'http://localhost:4000/api/lore';

export class CosmicLoreService {
  /**
   * Generate a single piece of cosmic lore
   */
  static async generateLore(request: LoreGenerationRequest): Promise<CosmicLore> {
    const response = await fetch(`${API_BASE_URL}/generate`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      throw new Error(`Failed to generate lore: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Generate a complete set of lore for a planet
   */
  static async generateLoreSet(planetData: LoreGenerationRequest['planetData']): Promise<CosmicLore[]> {
    const response = await fetch(`${API_BASE_URL}/generate-set`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ planetData }),
    });

    if (!response.ok) {
      throw new Error(`Failed to generate lore set: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Get AI recommendations for lore generation
   */
  static async getRecommendations(planetData: LoreGenerationRequest['planetData']): Promise<{
    category: CosmicLore['category'];
    reason: string;
  }[]> {
    const response = await fetch(`${API_BASE_URL}/recommendations`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ planetData }),
    });

    if (!response.ok) {
      throw new Error(`Failed to get recommendations: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Export lore to text format
   */
  static exportLore(loreList: CosmicLore[], filename?: string): void {
    const text = loreList.map(lore => 
      `${lore.title}\n` +
      `Category: ${lore.category} | Tone: ${lore.tone} | Length: ${lore.length}\n` +
      `Planet: ${lore.planetName}\n` +
      `Generated: ${new Date(lore.timestamp).toLocaleString()}\n` +
      `Tags: ${lore.tags.join(', ')}\n\n` +
      `${lore.content}\n\n` +
      `${'='.repeat(80)}\n\n`
    ).join('');
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename || `cosmic-lore-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  /**
   * Copy lore to clipboard
   */
  static async copyLore(lore: CosmicLore): Promise<void> {
    const text = `${lore.title}\n\n${lore.content}\n\nGenerated by Cosmic Lore AI • ${new Date(lore.timestamp).toLocaleString()}`;
    
    try {
      await navigator.clipboard.writeText(text);
    } catch (error) {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
    }
  }

  /**
   * Get sample planet data for testing
   */
  static getSamplePlanets(): LoreGenerationRequest['planetData'][] {
    return [
      {
        name: 'Kepler-452b',
        hostStar: 'Kepler-452',
        discoveryYear: 2015,
        discoveryMethod: 'Transit',
        planetRadius: 1.6,
        planetMass: 5.0,
        temperature: 265,
        distanceFromEarth: 1402,
        habitableZone: true,
        orbitalPeriod: 385
      },
      {
        name: 'Proxima Centauri b',
        hostStar: 'Proxima Centauri',
        discoveryYear: 2016,
        discoveryMethod: 'Radial Velocity',
        planetRadius: 1.1,
        planetMass: 1.3,
        temperature: 234,
        distanceFromEarth: 4.2,
        habitableZone: true,
        orbitalPeriod: 11.2
      },
      {
        name: 'TRAPPIST-1e',
        hostStar: 'TRAPPIST-1',
        discoveryYear: 2017,
        discoveryMethod: 'Transit',
        planetRadius: 0.92,
        planetMass: 0.77,
        temperature: 251,
        distanceFromEarth: 40.7,
        habitableZone: true,
        orbitalPeriod: 6.1
      },
      {
        name: 'HD 209458 b',
        hostStar: 'HD 209458',
        discoveryYear: 1999,
        discoveryMethod: 'Transit',
        planetRadius: 1.38,
        planetMass: 0.69,
        temperature: 1500,
        distanceFromEarth: 159,
        habitableZone: false,
        orbitalPeriod: 3.5
      }
    ];
  }

  /**
   * Validate planet data
   */
  static validatePlanetData(planetData: Partial<LoreGenerationRequest['planetData']>): string[] {
    const errors: string[] = [];
    
    if (!planetData.name || planetData.name.trim() === '') {
      errors.push('Planet name is required');
    }
    
    if (planetData.distanceFromEarth && planetData.distanceFromEarth < 0) {
      errors.push('Distance from Earth must be positive');
    }
    
    if (planetData.discoveryYear && (planetData.discoveryYear < 1990 || planetData.discoveryYear > new Date().getFullYear())) {
      errors.push('Discovery year must be between 1990 and current year');
    }
    
    if (planetData.temperature && planetData.temperature < 0) {
      errors.push('Temperature must be positive (Kelvin)');
    }
    
    return errors;
  }

  /**
   * Get category descriptions for UI
   */
  static getCategoryDescriptions(): Record<CosmicLore['category'], string> {
    return {
      description: 'Comprehensive overview of the planet\'s characteristics and features',
      history: 'Formation story and cosmic timeline of the world',
      civilization: 'Speculation about potential life and civilizations',
      environment: 'Climate, weather patterns, and surface conditions',
      mystery: 'Unexplained phenomena and scientific puzzles',
      discovery_story: 'The tale of how this world was found and confirmed'
    };
  }

  /**
   * Get tone descriptions for UI
   */
  static getToneDescriptions(): Record<CosmicLore['tone'], string> {
    return {
      scientific: 'Factual, data-driven approach with technical terminology',
      poetic: 'Lyrical and artistic descriptions that inspire wonder',
      mysterious: 'Enigmatic tone focusing on unknowns and possibilities',
      adventure: 'Exciting narrative that invites exploration',
      documentary: 'Informative style similar to nature documentaries'
    };
  }
}

export type { CosmicLore, LoreGenerationRequest };
