// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjozesrdjwoeiyidbzop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpqb3plc3JkandvZWl5aWRiem9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NzY4MDQsImV4cCI6MjA3MjQ1MjgwNH0.L-K74kJ_4FizzQzEqNqxKaMPF5sdusOo_1w6BfemvrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});